### ISSUE TITLE
NullPointerException while indexing

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#10]
After updating to latest nightly there still seem to be issues with indexing.
I get the following error:
![grafik](https://user-images.githubusercontent.com/6151929/54153959-207aea00-4441-11e9-9d7e-ce5ad78715e7.png)

I know text would be better than screenshots. What's your prefered way of getting those stacktraces @VISTALL?

I also get errors from XML plugin inside that php project:
![grafik](https://user-images.githubusercontent.com/6151929/54154182-9717e780-4441-11e9-8175-c0a7850fb985.png)

Should I also open an issue in XML repo?

**Comment by VISTALL** [comment]
Hello. You can just use button - Send report. I not often, but i check exception list, and fix them.

**Comment by Sajito** [comment]
I already did so. Is it useful for you if I put the generated issue hash to my issues here in github?

**Comment by VISTALL** [comment]
You don't need create gh issue for it :) I will fix today.. Thanks

**Comment by VISTALL** [comment]
Hello. I added debug for this situation - since i can't find way how reproduce it. After update it will contains text of expression (just submit exception to tracker)

Thanks

**Comment by Sajito** [comment]
> 
> 
> Hello. I added debug for this situation - since i can't find way how reproduce it. After update it will contains text of expression (just submit exception to tracker)
> 
> Thanks

I have submitted some exceptions to your tracker, but I think there is something wrong with your debug code:
![grafik](https://user-images.githubusercontent.com/6151929/54312031-2bb34e80-45d6-11e9-8861-7d240e74d67e.png)
