### ISSUE TITLE
Autocompletion not working

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#11]
Okay, I can open up a php project without having any exception and stubs are being added to project. Let's start reporting the issues.

Even though stubs are present in the project, I don't get any autocompletion at all.
![grafik](https://user-images.githubusercontent.com/6151929/54451447-28919d00-4753-11e9-9391-aed2d9b870f0.png)

Doesn't matter in which context I am, there are no completions.

**Comment by VISTALL** [comment]
Hello. PHP don't have base resolving. I will add base resolve in primary future, after understanding what i need todo.

Thanks for issue.

**Comment by Sajito** [comment]
Is that also the reason for indexing project files not working?
![grafik](https://user-images.githubusercontent.com/6151929/54452786-444a7280-4756-11e9-8be0-4a7495f49b3f.png)

**Comment by VISTALL** [comment]
Yeah. Looks like i need for now make file parsing more stable (there many parser issues) - i am collecting what current parser miss

**Comment by Sajito** [comment]
Anything I can provide to help you?

**Comment by VISTALL** [comment]
You can write issues like this https://github.com/consulo/consulo-php/issues/12

**Comment by VISTALL** [comment]
Hello. I started working on resolving (after parsing changes).

Stub completion was added (it's not correct)

TODO:

https://github.com/consulo/consulo-php/issues/21
https://github.com/consulo/consulo-php/issues/22
