### ISSUE TITLE
PHP 5.5 - yield

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#24]
Hi,
I'm glad to see your progress. Still a lot of work needed, I hope to have some sparetime in the future to have a look on the plugin. If I get some time, maybe I can prove some commits, to help improving php support.

Yield seems to be defined as constant. Should be handled similar to return.

```
foreach ($array as $element) {
    yield $element;
}
```

https://www.php.net/manual/en/language.generators.syntax.php#control-structures.yield

**Comment by VISTALL** [comment]
Hello. Thanks for reporting. More you find - more i fix :) (also i working on php too, but i saw not all bugs)
