### ISSUE TITLE
PHP stubs missing

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#25]
Hi,

this issues was already addressed once, but it seems to reappear. I'm not quite sure since when it's like this again, but adding php sdk to a project does not add the php stubs.
![grafik](https://user-images.githubusercontent.com/6151929/58368045-8e369e00-7ee7-11e9-9999-c93d54ff5e2e.png)

**Comment by VISTALL** [comment]
Hello. I had add some break change. Can you remove PHP bundle, and then add again?

**Comment by Sajito** [comment]
Already did that, before opening the issue, but still no stubs.

**Comment by VISTALL** [comment]
Can you find your plugin directory (https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

then search **consulo.php** directory, and show what you have inside?

Must be like this 

![](https://klikr.org/69121d947f49d79bd4e5cb553f56.png)

**Comment by Sajito** [comment]
It looks the same. Also php files and stubes are present inside.

**Comment by VISTALL** [comment]
Hello. That strange. Can you remove php bundle, and add it - then go Help-> Show Log In Explorer, and send me log file? 

(Also you can switch to nightly channel for last php build)

**Comment by Sajito** [comment]
Hi. Sorry for the really late reply. I already am using the nightly channel.
I did as you requested. I have attached the log file.
[consulo.log](https://github.com/consulo/consulo-php/files/3267025/consulo.log)

**Comment by VISTALL** [comment]
np. Strange there no prolems. can you show this page? 

![](https://klikr.org/1bddecd51387f8c418f26fa79a0e.png)

**Comment by Sajito** [comment]
It was empty, so I removed everything completely again from settings and added everything step by step again. Now stubs are loaded. Thank you!
