### ISSUE TITLE
Class member and methods not resolved correctly

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#26]
Consulo is unable to resolve class members or functions on `$this`. While `$this` is correctly resolved to being the current Class, there is no autocompletion at all. Moreover autocompletion on `self::` should only reference static methods and constants, but they reference every member and function instead:
![grafik](https://user-images.githubusercontent.com/6151929/58368179-b9ba8800-7ee9-11e9-9229-8825a034ea04.png)

**Comment by Sajito** [comment]
There is still some work needed. Should I open a new issue?

The autocompletion references class members with a leading $ sign, which is wrong:
![grafik](https://user-images.githubusercontent.com/6151929/58378398-48cfaa80-7f93-11e9-9d62-eebe2926ce9d.png)

Also the IDE can't resolve class params with the same name as a class member:
![grafik](https://user-images.githubusercontent.com/6151929/58378406-74eb2b80-7f93-11e9-9c5c-3f375adfb65f.png)

**Comment by VISTALL** [comment]
yeah. Create new issue. I'm working on completion
