### ISSUE TITLE
Support latest PHP

### ISSUE THREAD

**Issue by Sajito** [consulo/consulo-php#9]
The extension itself seems to be working, but it seems like latest supported php version is php 5.6. Maybe lower.

It would be nice to have support for php 7 and up.

**Comment by VISTALL** [comment]
Hello. I expected this issue, but can we do it in different way? Close this issue - and you will create smaller issues, for each missed features? (like spaceship operator, etc).

It will be easy for me, understand what i need todo.

Thanks

**Comment by Sajito** [comment]
I'm totally fine with that. There's one issue with the plugin though, which prevents me from opening specific issues as I don't know what's causing it. Maybe use this issue for initial support.

First I'm gonna tell you my current setup.
I'm on Windows 10 1809 using PHP 7.3.

I've used [composer](https://getcomposer.org/) to create a new Symfony project:
`composer create-project symfony/skeleton test`

Then I just opened the project in consulo. While indexing there are some errors, which all look like this:
![grafik](https://user-images.githubusercontent.com/6151929/54090632-80f12500-4376-11e9-8eac-a7c1998201f5.png)

After that one I will open an issue for every missing feature.
Is it fine to open new issues for questions about settings in Consulo, if they aren't clear?

**Comment by VISTALL** [comment]
We can use (https://discuss.consulo.io/c/php-world) More easy way, and without spamming in GH tracker

**Comment by VISTALL** [comment]
About lexer problem - i'm in progress for fixing it

**Comment by VISTALL** [comment]
Fixed problem (also fixed use problem).

Pushed to currect master and available at nightly channel (https://github.com/consulo/consulo/wiki/Update-channels)

Can you also add to issue link from official documentation? I'm don't have good experience with php, it will be helps. 

Thanks
